# Generated by Django 3.2.9 on 2021-12-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityofmedicines',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_recipe_need',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availabilityofmedicines',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='btest.medicine'),
        ),
        migrations.AlterField(
            model_name='availabilityofmedicines',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='btest.pharmacy'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='btest.category'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(max_length=50, verbose_name='Дозировка'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(max_length=50, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='volume',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='nearest_metro',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Ближайшая станция метро'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Номер'),
        ),
    ]
