# Generated by Django 3.2.9 on 2021-12-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_auto_20211204_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityOfMedicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Информация о наличии лекарств',
                'verbose_name_plural': 'Информация о наличии лекарств',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('dosage', models.CharField(max_length=50, verbose_name='Дозировка')),
                ('volume', models.CharField(max_length=50, verbose_name='Объем')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Производитель')),
                ('is_recipe_need', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='proj.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('nearest_metro', models.CharField(db_index=True, max_length=50, verbose_name='Ближайшая станция метро')),
            ],
            options={
                'verbose_name': 'Аптека',
                'verbose_name_plural': 'Аптеки',
                'ordering': ['-number'],
            },
        ),
        migrations.DeleteModel(
            name='Bb',
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
        migrations.AddField(
            model_name='availabilityofmedicines',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proj.medicine'),
        ),
        migrations.AddField(
            model_name='availabilityofmedicines',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proj.pharmacy'),
        ),
    ]
